export const REACT_APP_PUBLIC_GOOGLE_MAPS_API_KEY =
    process.env.REACT_APP_PUBLIC_GOOGLE_MAPS_API_KEY
export const REACT_APP_EMAIL_JS_SERVICE_ID =
    process.env.REACT_APP_EMAIL_JS_SERVICE_ID
export const REACT_APP_EMAIL_JS_TEMPLATE_ID =
    process.env.REACT_APP_EMAIL_JS_TEMPLATE_ID
export const REACT_APP_EMAIL_JS_PUBLIC_KEY =
    process.env.REACT_APP_EMAIL_JS_PUBLIC_KEY
